users:
	admin:
		state: present
		comment: "Administrator User"
shell: "/bin/bash"
		uid: 5110
		gid: 5110
		password: "<< PASSWORD >>"
		sshkey: "<< PUB_KEY >>"
	testuser:
		state: present
		comments: "Example User"
shell: "/bin/bash"
		uid: 510
		gid: 510
		password: "<< PASSWORD >>"
		sshkey: "<< PUB_KEY >>"
		
worker_processes: 4
worker_connections: 768
multi_accept: "on"
send_file: "on"
tcp_nopush: "on"
tcp_nodelay: "on"
keepalive_timeout: 65
types_hash_max_size: 2048
server_tokens: "off"
gzip: "on"

virtualhosts:
test1:
server_name: test.stunthamster.com
vhost_root: '/usr/share/nginx/test1'
test2:
server_name: test2.stunthamster.com
vhost_root: '/usr/share/nginx/test2'